CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    phonenumber VARCHAR(20),
    email VARCHAR(100) UNIQUE NOT NULL,
    pwd TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);