INSERT INTO part_categories (name) VALUES
('Motor'),
('Sistema de Transmisión'),
('Frenos'),
('Suspensión'),
('Dirección'),
('Sistema Eléctrico'),
('Batería'),
('Sistema de Encendido'),
('Sistema de Combustible'),
('Sistema de Escape'),
('Refrigeración del Motor'),
('Llantas'),
('Rines'),
('Neumáticos'),
('Carrocería'),
('Iluminación'),
('Interior'),
('Aire Acondicionado'),
('Filtros'),
('Aceites y Lubricantes'),
('Correas'),
('Sensores'),
('Sistema de Seguridad'),
('Vidrios y Espejos'),
('Puertas y Cerraduras'),
('Radiador'),
('Embrague'),
('Alternador'),
('Motor de Arranque'),
('Sistema de Audio'),
('Accesorios'),
('Herramientas'),
('Mantenimiento Preventivo'),
('Otros');