spring.application.name=app
#Conexion Bases de Datos
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.xcistkmidhimrvpegfnm
spring.datasource.password=Dr1v3D3n.###
spring.datasource.driver-class-name=org.postgresql.Driver

#Hikari Connection Pool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000

#Flyway
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
#logging.level.org.flywaydb=DEBUG

#Al retornar Errores, no debe Mostrarse el trace -> este incluye las entidades del sistema
server.error.include-stacktrace=never

#SECRET KEY JWT
api.security.token.service=mysecretkey1234567890

#Configuracion de Envio de Correos
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a7d160001@smtp-brevo.com
spring.mail.password=xsmtpsib-6aff6cda33bcb304d8f37c129cb352150e0927d26e15a3d3466b0593d36a0c11-KU9pULQACsVdsWUv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.ssl.trust=smtp-relay.brevo.com
spring.mail.properties.mail.smtp.ssl.checkserveridentity=false

#ApiKey de Carspecs
rapidapi.key=16572e408cmshd17ac619a61bca0p18fab9jsn4ad2184416de
rapidapi.host=car-specs.p.rapidapi.com